appName: bae-careers-rest-api
imageName: ymandrews/bae-careers-rest-api:1.0.4
replicas: 1
serviceName: bae-careers-rest-api-svc
hostName: api.careers.baesystems.com
sourcePort: 8080
targetPort: 8080
nodePort: 30003
postgresIP: 10.96.26.155
postgresPort: 5432
appVersion: 1.0.4
